name: Singer-Check-Tap

on: push

jobs:
  check-tap:
    name: Check Tap
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: x64

    - name: Install Poetry
      run: pip install poetry==1.1.5

    - name: Install Dependencies
      run: poetry install

    - name: Check Tap Output
      id: check-tap-output
      env:
        TAP_CONFLUENCE_base_url: ${{ secrets.CONFLUENCE_BASE_URL }}
        TAP_CONFLUENCE_email: ${{ secrets.CONFLUENCE_EMAIL }}
        TAP_CONFLUENCE_api_token: ${{ secrets.CONFLUENCE_API_TOKEN }}
        TAP_CONFLUENCE_resources: '[spaces, pages, blogposts, themes, groups]'
      run: echo "::set-output name=check-result::$(poetry run tap-confluence | poetry run singer-check-tap)"

    - name: Comment on PR
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ steps.check-tap-output.outputs.check-result }}',
          })
